version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  shopware:
    image: endereco/shopware_6.4.0_php_8.1:1.0.0
    environment:
      SHOP_URL: http://localhost
    volumes:
      - ./:/var/www/html/custom/plugins/EnderecoShopware6Client
    ports:
      - 80:80 # web ui
      - 443:443
    depends_on:
      mysql:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 # web ui
  mailhog:
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui