<?php

declare(strict_types=1);

namespace Endereco\Shopware6Client\Misc;

class EnderecoConstants
{
    public const STREET_ORDER_HOUSE_FIRST = 'house-first';
    public const STREET_ORDER_HOUSE_SECOND = 'house-second';
    public const STREET_ORDER_MAP = [
        'de' => self::STREET_ORDER_HOUSE_SECOND,
        'at' => self::STREET_ORDER_HOUSE_SECOND,
        'fr' => self::STREET_ORDER_HOUSE_FIRST,
        'us' => self::STREET_ORDER_HOUSE_FIRST,
        'dz' => self::STREET_ORDER_HOUSE_FIRST,
        'ad' => self::STREET_ORDER_HOUSE_FIRST,
        'az' => self::STREET_ORDER_HOUSE_FIRST,
        'am' => self::STREET_ORDER_HOUSE_FIRST,
        'au' => self::STREET_ORDER_HOUSE_FIRST,
        'bh' => self::STREET_ORDER_HOUSE_FIRST,
        'bd' => self::STREET_ORDER_HOUSE_FIRST,
        'bn' => self::STREET_ORDER_HOUSE_FIRST,
        'kh' => self::STREET_ORDER_HOUSE_FIRST,
        'ca' => self::STREET_ORDER_HOUSE_FIRST,
        'cn' => self::STREET_ORDER_HOUSE_FIRST,
        'cx' => self::STREET_ORDER_HOUSE_FIRST,
        'cc' => self::STREET_ORDER_HOUSE_FIRST,
        'cd' => self::STREET_ORDER_HOUSE_FIRST,
        'cg' => self::STREET_ORDER_HOUSE_FIRST,
        'ck' => self::STREET_ORDER_HOUSE_FIRST,
        'cy' => self::STREET_ORDER_HOUSE_FIRST,
        'ci' => self::STREET_ORDER_HOUSE_FIRST,
        'dm' => self::STREET_ORDER_HOUSE_FIRST,
        'eg' => self::STREET_ORDER_HOUSE_FIRST,
        'fj' => self::STREET_ORDER_HOUSE_FIRST,
        'ga' => self::STREET_ORDER_HOUSE_FIRST,
        'gm' => self::STREET_ORDER_HOUSE_FIRST,
        'ge' => self::STREET_ORDER_HOUSE_FIRST,
        'gh' => self::STREET_ORDER_HOUSE_FIRST,
        'gi' => self::STREET_ORDER_HOUSE_FIRST,
        'gp' => self::STREET_ORDER_HOUSE_FIRST,
        'gu' => self::STREET_ORDER_HOUSE_FIRST,
        'gy' => self::STREET_ORDER_HOUSE_FIRST,
        'hk' => self::STREET_ORDER_HOUSE_FIRST,
        'in' => self::STREET_ORDER_HOUSE_FIRST,
        'id' => self::STREET_ORDER_HOUSE_FIRST,
        'ie' => self::STREET_ORDER_HOUSE_FIRST,
        'gb' => self::STREET_ORDER_HOUSE_FIRST,
        'il' => self::STREET_ORDER_HOUSE_FIRST,
        'la' => self::STREET_ORDER_HOUSE_FIRST,
        'lb' => self::STREET_ORDER_HOUSE_FIRST,
        'lu' => self::STREET_ORDER_HOUSE_FIRST,
        'mr' => self::STREET_ORDER_HOUSE_FIRST,
        'mu' => self::STREET_ORDER_HOUSE_FIRST,
        'mc' => self::STREET_ORDER_HOUSE_FIRST,
        'ms' => self::STREET_ORDER_HOUSE_FIRST,
        'ma' => self::STREET_ORDER_HOUSE_FIRST,
        'mm' => self::STREET_ORDER_HOUSE_FIRST,
        'na' => self::STREET_ORDER_HOUSE_FIRST,
        'nz' => self::STREET_ORDER_HOUSE_FIRST,
        'ng' => self::STREET_ORDER_HOUSE_FIRST,
        'nf' => self::STREET_ORDER_HOUSE_FIRST,
        'om' => self::STREET_ORDER_HOUSE_FIRST,
        'pk' => self::STREET_ORDER_HOUSE_FIRST,
        'pw' => self::STREET_ORDER_HOUSE_FIRST,
        'ph' => self::STREET_ORDER_HOUSE_FIRST,
        'pr' => self::STREET_ORDER_HOUSE_FIRST,
        'rw' => self::STREET_ORDER_HOUSE_FIRST,
        're' => self::STREET_ORDER_HOUSE_FIRST,
        'bl' => self::STREET_ORDER_HOUSE_FIRST,
        'sh' => self::STREET_ORDER_HOUSE_FIRST,
        'kn' => self::STREET_ORDER_HOUSE_FIRST,
        'mf' => self::STREET_ORDER_HOUSE_FIRST,
        'sa' => self::STREET_ORDER_HOUSE_FIRST,
        'sn' => self::STREET_ORDER_HOUSE_FIRST,
        'sl' => self::STREET_ORDER_HOUSE_FIRST,
        'sg' => self::STREET_ORDER_HOUSE_FIRST,
        'tw' => self::STREET_ORDER_HOUSE_FIRST,
        'tz' => self::STREET_ORDER_HOUSE_FIRST,
        'th' => self::STREET_ORDER_HOUSE_FIRST,
        'tg' => self::STREET_ORDER_HOUSE_FIRST,
        'tt' => self::STREET_ORDER_HOUSE_FIRST,
        'tn' => self::STREET_ORDER_HOUSE_FIRST,
        'tm' => self::STREET_ORDER_HOUSE_FIRST,
        'tc' => self::STREET_ORDER_HOUSE_FIRST,
        'vm' => self::STREET_ORDER_HOUSE_FIRST,
        'wf' => self::STREET_ORDER_HOUSE_FIRST,
        'ye' => self::STREET_ORDER_HOUSE_FIRST,
        'zm' => self::STREET_ORDER_HOUSE_FIRST,
        'zw' => self::STREET_ORDER_HOUSE_FIRST,
    ];
}
